#!/usr/bin/perl 
use lib "$FindBin::Bin/lib/";  # use the parent directory
use POSIX;
use updateGeneLocat;
use FindBin;                 # locate this script
use MongoDB;
use initMongo;
use insertClinvarNames;
use insertRefseq;
use insertInteractions;
use insertVcf;
use insertTcgaMel;
use insertDbnsfpGene;
use insertCgd;
use insertToPanels;
use insertTwoCol;
use insertDbnsfp;
use insertGedi;
use insertLevel2;
use insertPli;
use insertDbscSNV1;
use insertUniprotAnnotate;
use insertDbnsfpGnomad;
use insertDiseaseDescription;

##$hostName='pbc-dcraig-login.tgen.org:27040';
##$hostName='pbc-dcraig-db1:26565';
##$hostName='localhost:27030';
$hostName='labdb01.tgen.org:28555';
#insertVcf->loadTo ('/data/db/annotations/temp/dbsnp/20180418/All_20180418.vcf','coord',$hostName,'dbsnp');
insertVcf->loadTo ('db/clinvar/clinvar_20190805.vcf','coord',$hostName,'clinvar2019');
#insertVcf->loadTo ('db/clinvar/common_and_clinical_20170705.vcf','coord',$hostName,'clinvar');
#insertVcf->loadTo('db/1kg/KG3.head.mPASS.vcf','coord',$hostName,'phase3KG');
##insertVcf->loadTo('db/ExAc/ExAC.r0.3.sites.vep.vcf','coord',$hostName,'ExAc');
#insertVcf->loadTo('db/cosmic/v82/CosmicCodingMuts.vcf','coord',$hostName,'cosmicCoding');
#insertVcf->loadTo('/data/db/annotations/temp/gnomad/2.0.2/gnomad.genomes.r2.0.2.sites.liftover.b38.autosomes_and_X.vcf','coord',$hostName,'gnomad');
#print "finished loading dbsnp\n";
#insertVcf->loadTo('db/cosmic/v82/CosmicNonCodingVariants.vcf','coord',$hostName,'cosmicNonCoding');
##print "finished loading cosmicNonCodingVariants\n";
#insertDbnsfpGnomad->loadTo ('db/dbnsfp3.5/dbNSFP*.chr*','coord',$hostName);
#print "finished loading dbnsfp3.4\n";
#insertDbscSNV1->loadTo ('db/dbnsfp3.4/dbscSNV1.1*','coord',$hostName);
#print "finished loading dbscSNV1\n";
#initMongo->removeEntries('AnnotateBy','gene',$hostName);;
#initMongo->removeEntries('AnnotateBy','geneCodon',$hostName);;
#insertUniprotAnnotate->loadTo('db/uniprot/uniprot_sprot.xml','gene',$hostName);
#insertDiseaseDescription->loadTo('db/genes/descriptions.csv','gene',$hostName,'descriptions');
#insertTwoCol->loadTo('db/genes/orphanet.txt','gene',$hostName,'orphanet');
#insertTwoCol->loadTo('db/genes/genecards.txt','gene',$hostName,'genecards');
#insertTwoCol->loadTo('db/genes/CTD.parse.txt','gene',$hostName,'diseaseKeywords');
#insertTwoCol->loadTo('db/genes/refseq.txt','gene',$hostName,'geneSummary');
#insertDbnsfpGene->loadTo ('db/genes/dbNSFP3.5_gene.complete','gene',$hostName);
#insertTwoCol->loadTo('db/genes/go_ontology.txt','gene',$hostName,'goOntology');
#insertTwoCol->loadTo('db/genes/isca.txt','gene',$hostName,'isca');
#insertToPanels->loadTo('db/genes/mito100.txt','gene',$hostName,'mito100');
#insertToPanels->loadTo('db/genes/acmg.txt','gene',$hostName,'acmg');
#insertToPanels->loadTo('db/genes/epilepsy.txt','gene',$hostName,'epilepsy');
#insertToPanels->loadTo('db/genes/gedi.txt','gene',$hostName,'gedi');
#insertToPanels->loadTo('db/genes/mitocarta.txt','gene',$hostName,'mitocarta');
#insertToPanels->loadTo('db/genes/foundation.txt','gene',$hostName,'foundationOne');
#insertToPanels->loadTo('db/genes/hypoplasia.txt','gene',$hostName,'hypoplasia');
#insertToPanels->loadTo('db/genes/illumina.txt','gene',$hostName,'illumina');
#insertToPanels->loadTo('db/genes/ion.txt','gene',$hostName,'ion');
#insertPli->loadTo('db/ExAc/pLI.tsv','gene',$hostName,'pLI');
#insertToPanels->loadTo('db/genes/tcga-gbm.txt','gene',$hostName,'tcga-gbm');
#insertCgd->loadTo ('db/genes/cgd.txt','gene',$hostName);
#insertTcgaMel->loadTo ('db/tcga/PR_TCGA_SKCM_PAIR_Capture_All_Pairs_QCPASS.aggregated.capture.tcga.uuid.somatic.maf.csv','tcga',$hostName);
#insertTwoCol->loadTo('db/genes/level2.txt','gene',$hostName,'level2');
#insertTwoCol->loadTo('db/genes/pharmkgb.txt','gene',$hostName,'pharmkgb');
#insertClinvarNames->loadTo('db/genes/clinvar.txt','gene',$hostName);
#insertToPanels->loadTo('db/genes/level2.txt','gene',$hostName,'level2');
#insertRefseq->loadTo('db/refseq/refSeqSummary.txt','gene',$hostName);
print "inserted everything\n";
